version: '3.4'

networks:
    default:
        external:
            name: ${NETWORK_NAME}

volumes:
    mysql:
        external:
            name: ${COMPOSE_PROJECT_NAME}-mysql
    elasticsearch:
        external:
            name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    redis:
        external:
            name: ${COMPOSE_PROJECT_NAME}-redis

services:
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        restart: always
        image: ekyna/mysql:${MYSQL_VERSION}
        working_dir: /root
        environment:
            TZ: ${TIMEZONE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        cap_add:
            - SYS_NICE
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - mysql:/var/lib/mysql:rw
        healthcheck:
            interval: 10s
            timeout: 2s
            retries: 3
            start_period: 30s
        logging:
            driver: "json-file"
            options: { max-size: "5m", max-file: "3" }
        networks:
            default:
                aliases:
                    - mysql.${COMPOSE_PROJECT_NAME}

    elasticsearch:
        container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
        restart: always
        image: ekyna/elasticsearch:${ELASTICSEARCH_VERSION}
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data:rw
        environment:
            - TZ=${TIMEZONE}
            - cluster.name=${COMPOSE_PROJECT_NAME}-cluster
            - discovery.type=single-node
            - xpack.security.enabled=false
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true
        cap_add:
            - IPC_LOCK
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        healthcheck:
            interval: 10s
            timeout: 2s
            retries: 3
            start_period: 30s
        logging:
            driver: "json-file"
            options: { max-size: "2m", max-file: "3" }
        networks:
            default:
                aliases:
                    - elasticsearch.${COMPOSE_PROJECT_NAME}

    chrometopdf:
        container_name: ${COMPOSE_PROJECT_NAME}_chrometopdf
        restart: always
        image: ekyna/chrome-to-pdf:latest
        environment:
            TZ: ${TIMEZONE}
            AUTH_TOKEN: ${CHROME_TO_PDF_TOKEN}
        logging:
            driver: json-file
            options: { max-size: "2m", max-file: "3" }
        healthcheck:
            interval: 10s
            timeout: 2s
            retries: 3
            start_period: 10s
        networks:
            default:
                aliases:
                    - chrometopdf.${COMPOSE_PROJECT_NAME}

    redis:
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        restart: always
        image: redis:${REDIS_VERSION}
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - redis:/data:rw
        logging:
            driver: "json-file"
            options: { max-size: "2m", max-file: "3" }
        networks:
            default:
                aliases:
                    - redis.${COMPOSE_PROJECT_NAME}
