version: '2'

networks:
    default:
        external:
            name: "${NETWORK_NAME}"

services:
    # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
    phpmyadmin:
        container_name: "${COMPOSE_PROJECT_NAME}_phpmyadmin"
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        ports:
            - "${PHPMYADMIN_PORT}:80"
        external_links:
            - "${COMPOSE_PROJECT_NAME}_mysql:mysql"
